<template>
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" class="text-orange-600">
    <line
      x1="12"
      y1="20"
      x2="12"
      y2="10"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <line
      x1="18"
      y1="20"
      x2="18"
      y2="4"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <line
      x1="6"
      y1="20"
      x2="6"
      y2="16"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
  </svg>
</template>
